# library(remotes)
# install_version("ggrepel", "0.9.6", repos='http://cran.us.r-project.org')
# install_version("rlang", "1.1.6", repos='http://cran.us.r-project.org')
# install.packages(c("BiocManager", "dplyr", "readr", "stringr", "purrr"), repos='http://cran.us.r-project.org')
# BiocManager::install("VariantAnnotation")
devtools::install_github("jean997/GFA")
# devtools::install_github("mrcieu/gwasvcf")
# devtools::install_github("mrcieu/ieugwasr")